### ISSUE TITLE
Help in generating Jenkins DSL for this plugin

### ISSUE THREAD

**Issue by syedshariq-a** [loren138/jenkins-commit-message-trigger-plugin#1]
Hey, can anyone help us in enabling this plugin as well as adding keyword via Jenkins DSL/XML declarative format?

We tried it, however, it was overwriting the git branch and git credentials block for some reason.

Would appreciate some help regarding this.

Thanks

**Comment by loren138** [comment]
Closing because I'm archiving this repository feel free to fork it/otherwise update it to work for you
